services:
  django-ern:
    # image: european-researchers-night-software-django-ern:latest
    build: .
    ports:
      - '8000:8000'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db:/usr/src/app/db/
    environment:
      DEBUG: "False"
      OPENAPI_HOST: "http://host.docker.internal"
      ALLOWED_HOST: "https://ern.darwinkel.net"
volumes:
  db: