# Generated by Django 5.1.1 on 2024-09-29 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('P', 'Prefer not to say'), ('O', 'Other/Unspecified'), ('M', 'Male'), ('F', 'Female')], default='P', max_length=1)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('story_text', models.CharField(max_length=2000)),
                ('human_shuffled_story', models.CharField(max_length=2500)),
                ('random_shuffled_story', models.CharField(max_length=2500)),
                ('rating_reconstructed_random_niceness', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_human_quality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_human_niceness', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English')], default='nl', max_length=2)),
                ('llm_reconstructed_human_story', models.CharField(default='', max_length=2500)),
                ('llm_reconstructed_random_story', models.CharField(default='', max_length=2500)),
                ('rating_reconstructed_random_quality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('human_shuffled_story_difficulty', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
