# Generated by Django 5.0.7 on 2024-07-30 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('P', 'Prefer not to say'), ('O', 'Other/Unspecified'), ('M', 'Male'), ('F', 'Female')], default='P', max_length=1)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('story_text', models.CharField(max_length=500)),
                ('human_shuffled_story', models.CharField(max_length=500)),
                ('random_shuffled_story', models.CharField(max_length=500)),
                ('rating_reconstructed_human_fluency', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_human_flow', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_human_accuracy', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', models.CharField(choices=[('nl', 'Nederlands'), ('en', 'English')], default='nl', max_length=2)),
                ('llm_reconstructed_human_story', models.CharField(default='', max_length=500)),
                ('llm_reconstructed_random_story', models.CharField(default='', max_length=500)),
                ('rating_reconstructed_random_accuracy', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_random_flow', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_reconstructed_random_fluency', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('human_shuffled_story_difficulty', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
