# Generated by Django 5.1.1 on 2024-09-20 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_squashed_0007_sample_human_shuffled_story_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
