# Generated by Django 5.1.1 on 2024-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_sample_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='human_shuffled_story',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='sample',
            name='llm_reconstructed_human_story',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='sample',
            name='llm_reconstructed_random_story',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='sample',
            name='random_shuffled_story',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='sample',
            name='story_text',
            field=models.CharField(max_length=2000),
        ),
    ]
