# Generated by Django 5.1.1 on 2024-09-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_sample_human_shuffled_story_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='rating_reconstructed_human_accuracy',
            new_name='rating_reconstructed_human_niceness',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='rating_reconstructed_human_flow',
            new_name='rating_reconstructed_human_quality',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='rating_reconstructed_human_fluency',
            new_name='rating_reconstructed_random_niceness',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='rating_reconstructed_random_accuracy',
            new_name='rating_reconstructed_random_quality',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='rating_reconstructed_random_flow',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='rating_reconstructed_random_fluency',
        ),
    ]
